In [38]:
import numpy as np
import matplotlib.pyplot as plt

In [11]:
def Calculate1DField(ey, hz):
    if len(ey) != len(hz):
        return None
    for i in range(len(ey)-1):
        ey[i+1] += (hz[i] - hz[i+1]) / Z0
    for i in range(len(hz)-1):
        hz[i] += (ey[i] - ey[i+1]) * Z0

In [270]:
Z0 = 1 #377 # сопротивление среды 120pi

N = 10 # число точек

Ey = np.zeros(N)
Hz = np.zeros(N)

step_count = 50 # шаг по времени, количество отсчётов dt
Ey[1] = 1

for i in range(step_count):
    CalculateField(Ey, Hz)
    print(Hz)

[-1.  1.  0.  0.  0.  0.  0.  0.  0.  0.]
[ 0. -1.  1.  0.  0.  0.  0.  0.  0.  0.]
[ 0.  0. -1.  1.  0.  0.  0.  0.  0.  0.]
[ 0.  0.  0. -1.  1.  0.  0.  0.  0.  0.]
[ 0.  0.  0.  0. -1.  1.  0.  0.  0.  0.]
[ 0.  0.  0.  0.  0. -1.  1.  0.  0.  0.]
[ 0.  0.  0.  0.  0.  0. -1.  1.  0.  0.]
[ 0.  0.  0.  0.  0.  0.  0. -1.  1.  0.]
[ 0.  0.  0.  0.  0.  0.  0.  0. -1.  0.]
[ 0.  0.  0.  0.  0.  0.  0.  0. -1.  0.]
[ 0.  0.  0.  0.  0.  0.  0. -1.  1.  0.]
[ 0.  0.  0.  0.  0.  0. -1.  1.  0.  0.]
[ 0.  0.  0.  0.  0. -1.  1.  0.  0.  0.]
[ 0.  0.  0.  0. -1.  1.  0.  0.  0.  0.]
[ 0.  0.  0. -1.  1.  0.  0.  0.  0.  0.]
[ 0.  0. -1.  1.  0.  0.  0.  0.  0.  0.]
[ 0. -1.  1.  0.  0.  0.  0.  0.  0.  0.]
[-1.  1.  0.  0.  0.  0.  0.  0.  0.  0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[ 1. -1.  0.  0.  0.  0.  0.  0.  0.  0.]
[ 0.  1. -1.  0.  0.  0.  0.  0.  0.  0.]
[ 0.  0.  1. -1.  0.  0.  0.  0.  0.  0.]
[ 0.  0.  0.  1. -1.  0.  0.  0.  0.  0.]
[ 0.  0.  0.  0.  1. -1.  0.  0.  0.  0.]
[ 

In [294]:
def Calculate2DField(e, h):
    nx = len(e[0])
    ny = len(e[0][0])
    (Ex, Ey, Ez) = e
    (Hx, Hy, Hz) = h    
    for i in range(nx - 1):
        for j in range(ny - 1):
            Ex[i+1][j+1] +=  (Hz[i][j+1] - Hz[i][j]) / Z0
            Ey[i+1][j+1] += -(Hz[i+1][j] - Hz[i][j]) / Z0
            Ez[i+1][j+1] += ((Hy[i+1][j] - Hy[i][j]) - (Hx[i][j+1] - Hx[i][j])) / Z0
    for i in range(nx - 1):
        for j in range(ny - 1):
            Hx[i]  [j]   -=  (Ez[i][j+1] - Ez[i][j]) * Z0
            Hy[i]  [j]   -= -(Ez[i+1][j] - Ez[i][j]) * Z0
            Hz[i]  [j]   -= ((Ey[i+1][j] - Ey[i][j]) - (Ex[i][j+1] - Ex[i][j])) * Z0
    

# Ex[10][10] = 1

# step_count = 3

# for i in range(step_count):
#     Calculate2DField(E,H)

# print(Ex)

In [298]:
Nx = 5
Ny = 5

Ex = np.zeros((Nx,Ny))
Ey = np.zeros((Nx,Ny))
Ez = np.zeros((Nx,Ny))

Hx = np.zeros((Nx,Ny))
Hy = np.zeros((Nx,Ny))
Hz = np.zeros((Nx,Ny))

E = (Ex, Ey, Ez)
H = (Hx, Hy, Hz)

for i in range(Nx-1):
    Ey[1][i+1] = 1
step_count = 1

for i in range(step_count):
    Calculate2DField(E,H)

print("Ex")
print(Ex)
print("Ey")
print(Ey)

print("Hz")
print(Hz)

# fig, ax = plt.subplots()
# ax.imshow(Ez)
# fig.set_figwidth(12)    #  ширина и
# fig.set_figheight(12)    #  высота "Figure"
# plt.show()

Ex
[[ 0.  0.  0.  0.  0.]
 [ 0. -1.  0.  0.  1.]
 [ 0.  1.  0.  0. -1.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]
Ey
[[ 0.  0.  0.  0.  0.]
 [ 0.  1. -1. -1. -1.]
 [ 0.  0.  1.  1.  1.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]
Hz
[[ 0. -1. -1. -1.  0.]
 [ 0.  1.  1.  1.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]
