In [1]:
import numpy as np


In [7]:
Z0 = 377 # сопротивление среды 120pi

N = 10 # число точек

Ey = np.zeros(N)
Hz = np.zeros(N)

def CalculateField(ey, hz):
    if len(ey) != len(hz):
        return None
    for i in range(len(ey)-1):
        ey[i+1] += (hz[i] - hz[i+1]) / Z0
    for i in range(len(hz)-1):
        hz[i] += (ey[i] - ey[i+1]) * Z0


step_count = 50 # шаг по времени, количество отсчётов dt
Ey[1] = 1

for i in range(step_count):
    CalculateField(Ey, Hz)
    print(Hz)

[-377.  377.    0.    0.    0.    0.    0.    0.    0.    0.]
[   0. -377.  377.    0.    0.    0.    0.    0.    0.    0.]
[   0.    0. -377.  377.    0.    0.    0.    0.    0.    0.]
[   0.    0.    0. -377.  377.    0.    0.    0.    0.    0.]
[   0.    0.    0.    0. -377.  377.    0.    0.    0.    0.]
[   0.    0.    0.    0.    0. -377.  377.    0.    0.    0.]
[   0.    0.    0.    0.    0.    0. -377.  377.    0.    0.]
[   0.    0.    0.    0.    0.    0.    0. -377.  377.    0.]
[   0.    0.    0.    0.    0.    0.    0.    0. -377.    0.]
[   0.    0.    0.    0.    0.    0.    0.    0. -377.    0.]
[   0.    0.    0.    0.    0.    0.    0. -377.  377.    0.]
[   0.    0.    0.    0.    0.    0. -377.  377.    0.    0.]
[   0.    0.    0.    0.    0. -377.  377.    0.    0.    0.]
[   0.    0.    0.    0. -377.  377.    0.    0.    0.    0.]
[   0.    0.    0. -377.  377.    0.    0.    0.    0.    0.]
[   0.    0. -377.  377.    0.    0.    0.    0.    0.    0.]
[   0. -